namespace Caddx_PCTool;

public enum AR_COMMAND : uint
{
	unkown_cmd = 0u,
	AR_COMMAND_REBOOT = 3u,
	AR_COMMAND_FIND_DEVICE = 60u,
	AR_COMMAND_REMOTE_UPGRADE = 114u,
	AR_CMD_SENDFILE_START = 115u,
	AR_CMD_SENDFILE_DATA = 116u,
	AR_CMD_SENDFILE_END = 117u,
	AR_CMD_UPGRADE_STATUS = 118u
}
