<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>Caddx PC Tool</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup />
  <ItemGroup>
    <Reference Include="AntdUI_Ex" />
    <Reference Include="Newtonsoft.Json" />
    <Reference Include="System.Core">
      <HintPath>../../usr/lib/dotnet/shared/Microsoft.NETCore.App/10.0.11/System.Core.dll</HintPath>
    </Reference>
    <Reference Include="System.Management" />
    <Reference Include="System.Xml">
      <HintPath>../../usr/lib/dotnet/shared/Microsoft.NETCore.App/10.0.11/System.Xml.dll</HintPath>
    </Reference>
    <Reference Include="PdfiumViewer" />
    <Reference Include="Velopack" />
    <Reference Include="System.Configuration">
      <HintPath>../../usr/lib/dotnet/shared/Microsoft.NETCore.App/10.0.11/System.Configuration.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>