<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Mono.Cecil">
      <HintPath>/home/seriy/.dotnet/tools/.store/ilspycmd/11.0.0.9375/ilspycmd/11.0.0.9375/tools/net10.0/any/Mono.Cecil.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
